name: nats-cluster
description: NATS messaging cluster with 3 replicas and clustering configuration
version: 1.2.0
author: process-compose-community
tags:
  - messaging
  - nats
  - cluster
  - pubsub
  - microservices
last_updated: 2025-01-15T10:30:00Z
min_version: "0.50.0"
repository: https://github.com/f1bonacc1/process-compose-recipes