name: postgres-basic
description: Basic PostgreSQL database server with initialization script support
version: 1.2.0
author: process-compose-community
tags:
  - database
  - postgres
  - sql
  - basic
last_updated: 2025-08-06T20:30:00Z
min_version: "0.50.0"
repository: https://github.com/f1bonacc1/process-compose-recipes